USE [master]
GO

/****** Object:  Database [UserData]    Script Date: 11.04.2024 19:34:34 ******/
CREATE DATABASE [UserData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UseeData', FILENAME = N'D:\Database\UseeData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UseeData_log', FILENAME = N'D:\Database\UseeData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserData] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserData] SET  MULTI_USER 
GO

ALTER DATABASE [UserData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UserData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UserData] SET QUERY_STORE = ON
GO

ALTER DATABASE [UserData] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [UserData] SET  READ_WRITE 
GO

